name: Build and Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
      body:
        description: "Release description"
        default: ""

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

      - name: Build
        shell: bash
        run: |
          chmod +x build.sh
          bash build.sh \
            ${{ 
            matrix.os == 'windows-latest' && 'windows' ||
            matrix.os == 'ubuntu-latest' && 'linux' ||
            'macos'
            }}

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: |
            releases/*.tar.gz
            releases/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: release-files

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.body }}
          files: |
            release-files/*.tar.gz
            release-files/*.zip
          generate_release_notes: true